---
label-mode: segmentation
input_path: "/home/phiuser/projects/sentinel-labeling/examples"
project_path: "/home/phiuser/projects/sentinel-labeling/"
first_guess_available: False
classes:
- name: Clear
  description: All clear pixels, i.e. without cloud contamination or cloud shadows.
  colour:
  - 255
  - 255
  - 255
  - 0
  user_colour:
  - 0
  - 255
  - 255
  - 70
- name: Thick Cloud
  description: All cloudy pixels covered by thick clouds (does not include semi-transparent clouds or cloud shadows).
  colour:
  - 255
  - 255
  - 0
  - 70
- name: Thin Cloud
  description: Clouds that are semi-transparent, i.e. one can see land or sea surfaces through them. If a thin cloud lays over a thick cloud, please paint them with the <i>Thick Cloud</i> class.
  colour:
  - 0
  - 255
  - 0
  - 70
- name: Cloud Shadows
  description: All pixels contaminated by cloud shadows (not terrain shadows).
  colour:
  - 255
  - 0
  - 0
  - 70
- name: No data
  description: Reserved for no data pixels, e.g. pixels outside of the satellite's swath.
  colour:
  - 50
  - 50
  - 255
  - 70
tile_shape:
- 1280
- 1280
# If you want to allow the users only to label a subset of the tile:
mask_area:
- 128
- 128
- 1152
- 1152
views:
- name: Cirrus
  description: In this band combination vegetation appears in shades of red, soils
    vary from dark to light brown and urban areas are cyan blue. Snow, ice, and clouds
    are <b>light cyan or white</b>.
  channels:
  - (B10*70)
  - (B10*70)
  - (B10*70)
- name: RGB
  description: Normal RGB image.
  channels:
  - B05
  - B03
  - B02
- name: Snow vs. Clouds
  description: Small ice crystals in high-level clouds appear reddish-orange or peach,
    and thick ice snow looks vivid red (or red-orange). Bare soil appears bright cyan
    and vegetation seem greenish in the image. Water on the ground is very dark as
    it absorbs the SWIR and the red, but small (liquid) water drops in the clouds
    scatter the light equally in both visible and the SWIR, and therefore it appears
    white. Water Sediments are displayed as dark red.
  channels:
  - B01
  - B11
  - B12
